version: '3'

services:
  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  web:
    build: .
    #First run command
    command: bash -c "/myapp/bootstrap.sh"
    #Run server
    #command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    #command: bash -c "rm -f tmp/pids/server.pid && bundle && exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      #- D:/dev/ga/bundles:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

#https://docs.docker.com/compose/compose-file/#volumes
volumes:
  dbdata: